apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.x
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    serviceAccount:
      create: true
      name: external-secrets-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::676045246387:role/ESOServiceAccountRole
