apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cortex-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: cortex-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Merge
      data:
        DB_URL: "jdbc:mysql://{{ .DB_HOST }}:3306/camunda?autoReconnect=true&sessionVariables=transaction_isolation=READ-COMMITTED"
  data:
    - secretKey: DB_USER
      remoteRef:
        key: cortex-database-app-secret-${stage}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cortex-database-app-secret-${stage}
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: cortex-database-secret
        property: host
